name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential mingw-w64

    - name: Build
      run: |
        make

    - name: List Files
      run: |
        ls -R

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: ./doltool.exe
        retention-days: 1
