name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: ./build/your_executable_name.exe
        retention-days: 1
